language: php

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - '7.4snapshot'

before_install:
    - composer self-update
    - composer global require hirak/prestissimo
    - composer install

jobs:
    include:
        - stage: phpcs
          script: ./vendor/bin/phpcs src
